---
- name: reload facts
  setup: filter='*'

- name: Create zabbix agent dir for scripts
  file: path=/etc/zabbix/script/elastichead state=directory mode=755 owner=root group=root

- name: Copy redis scripts for monitoring
  copy: src=elastichead_zabbix dest=/etc/zabbix/script/elastichead/elastichead_zabbix mode=755 owner=root group=root

- name: Add crontab to elastichead monitoring
  cron: name="ElasticHead Zabbix sender" minute=*/5 cron_file=zabbix user=zabbix job="/etc/zabbix/script/elastichead/elastichead_zabbix --zabbix {{ zabbix_server }}"
